### ISSUE TITLE
Hardcoded host

### ISSUE THREAD

**Issue by siguycmo** [dayallnash/php-calculator#1]
https://github.com/dayallnash/php-calculator/blob/14683616c555fc93f512c8fbe32a36e25d6dfefa/js/calculator.js#L73

**Comment by dayallnash** [comment]
Commit [06ab39b ](https://github.com/dayallnash/php-calculator/commit/06ab39b2bc9e165d7150a2a1085493816143e108) fixes this issue.

Directory structure of calculator (from root) should be:

'/var/www/php-calculator/...'
